### ISSUE TITLE
new plate viewer node instance has no readout selected per default

### ISSUE THREAD

**Issue by niederle** [knime-mpicbg/HCS-Tools#1]
I would propose to make all double and integer columns as default readouts. factors and reference groups can stay without any default selection.

**Comment by fmeyenhofer** [comment]
When I drag a new node on the workbench, connect it and open the configuration dialog, the double and integer readouts are selected, the factors do not have a selection and the controls do not have a default selection either. So I find exactly the conditions as you described them.

Maybe we work on different version? I tested the de.mpicbg.tds.knime.hcstools_1.3.0.201302042357 which you can find on www.katzenplatz.ch/~knime/cbg/ using the update mechanism of eclipse.

**Comment by niederle** [comment]
but this selection is not set if the configuration dialog is not opened at all. New node + execute an open view will not work.

**Comment by fmeyenhofer** [comment]
as I said, I find exactly the conditions you described when I try it on my mac. Could you send me a copy of your workflow?

**Comment by niederle** [comment]
I'll send you the workflow. Just try to execute the plateviewer node WITHOUT (!) opening the config dialog. I get this warning that there are no readouts selected (see screenshot).
![Screen shot 2013-03-25 at 9 53 24 AM](https://f.cloud.github.com/assets/740926/297162/ff1f2adc-9529-11e2-98b6-08909f333870.png)

**Comment by fmeyenhofer** [comment]
The default parameter selection is passed on now without having to first open den nodes configuration dialog.
