### ISSUE TITLE
Expand Well Position doesnt work with sortable wells from Create Well Position

### ISSUE THREAD

**Issue by stoeter** [knime-mpicbg/HCS-Tools#103]
The Created Well Position node adds a space (" ") in from of the well to make wells sortable in case of 1536 format (e.g. " E08" and "AB05").
That space seems to confuse the Expand Well Position node, maybe a "strip" for the well collumn could solve that!?

**Comment by LauLauThom** [comment]
Hello,
I had the same issue since my filename are such that the well positions contain leading 0 to keep the same number of characters for the full string (ex : A001, A010, A100). It would be nice if the Expand Well Position node could cope with that.
Thanks a lot !
