### ISSUE TITLE
CV node needs 'barcode' column

### ISSUE THREAD

**Issue by stoeter** [knime-mpicbg/HCS-Tools#113]
The node gives this error if no column "barcode" in in the table:

Configure failed (IllegalArgumentException): Could not find attribute-column with name 'barcode'

Also it should be possible to have a "No Grouping" in the Group well by and the subset selection.

**Comment by niederle** [comment]
solved with new version of that node (released by 87e693590aba163afa09b55489d82f8f4bb00358)
