### ISSUE TITLE
How to display Well images in Plate Heatmap Viewer?

### ISSUE THREAD

**Issue by dlogan** [knime-mpicbg/HCS-Tools#119]
Plate Heatmap Viewer says it supports viewing images ("Tables containing images allow visualization of the well images in the well detail view."), but it is not working for me.  I am not understanding what format the images need to be in.  

I have saved PNGs, output from a CellProfiler SaveImages module, and I'd like to display them in Plate Heatmap Viewer.  The Docs say "Any cell of an image data column will be visualized", and I have a column in my input that is a full folder and file path to my images, but I suspect that this is not the right format.  Can you help give me any tip? Thanks!

**Comment by stoeter** [comment]
This issue was answered in KNIME forum:
https://forum.knime.com/t/how-to-display-well-images-in-plate-heatmap-viewer/33186
There must be a column with images instead just paths.
