### ISSUE TITLE
bug in re-opening single plate view

### ISSUE THREAD

**Issue by stoeter** [knime-mpicbg/HCS-Tools#16]
I saw that opening a single plate with right-click, closing it and re-opening the same plate again, doesn't work (nothing happens). Closing the plate view and "view" without reexcecuting gives access to same plate again.

**Comment by fmeyenhofer** [comment]
Yep, that was a stupid little bug that I stumbled across myself...
It has been fixed in commit 80af0c4a70a31c4a672751a90390e569ea755c28
