### ISSUE TITLE
images in plate viewer

### ISSUE THREAD

**Issue by stoeter** [knime-mpicbg/HCS-Tools#17]
I checked all three image configurations:
.img+, works, but no way, takes too much temp disk space
.png, works nicely, minimal disk space
Image file Linker, works, no disk space but would be nice if image would be scales/enlarged (can image size be configured somewhere?)

**Comment by fmeyenhofer** [comment]
The problem with the img+ cells I tried to discribe in the issue #12 and I am currently on working on a third attempt to get around this (together with Martin Horn from Konstanz).
There is no scaling of the images in the WellViewer. The idea is to get an overview. To have a closer look at the images, the idea would be to do this via HiLiting in combination with the ImageCellViewer. This feature has to be implemented though in the ImageProcessing Toolbox, but it's work in progress...

**Comment by fmeyenhofer** [comment]
After discussions with the KNIMErs and the KNIPers it came out that the this won't be changed: The "Reader Node" creating the img+ cells always has to generate temporary data, it generates thumbnails for a quick access on the images. 

In the help of the HeatMap Viewer it is explicitly said to use the Image File Linker, which is exactly for the purpose we need it. Contrary to image processing we only need reading access and it is still quick enough if the content is read from the disk once it is rendered.
