### ISSUE TITLE
Join Layout bug on identical layout names

### ISSUE THREAD

**Issue by niederle** [knime-mpicbg/HCS-Tools#23]
If a name of a layout layer is identical it seems to ignore it (uses only the unique names!?), and assigns the next unique layer name to the next layer data, which is wrong. I attached a layout with that problem.

Attachment: 130805HIPPO_HepG2_YAP-AB.xlsx

**Comment by niederle** [comment]
node should not accept it (layer names need to be unique) and throw an exception with a meaningful error-message.

**Comment by timnicolaisen** [comment]
fixed and need to be merged from branch Join_Layout_#23
