### ISSUE TITLE
single plate view is a bit slow

### ISSUE THREAD

**Issue by niederle** [knime-mpicbg/HCS-Tools#4]
when shwoing a single plate, I can see the wells filled one by one with its color. This takes not much time but much more than expected (I would assume if the whole screen can be displayed immediately, a single plate should be even faste)
![Screen shot 2013-02-13 at 10 34 21 AM](https://f.cloud.github.com/assets/740926/152350/4a4b08f6-75c1-11e2-8993-948a23ec1f99.png)

**Comment by fmeyenhofer** [comment]
I had not noticed this until recently myself. I checked the old version of the PlateViewer (ScreenExplorer) and noticed that it has the same issue. It's very slow for the first PlateViewer that is opened, then the second instance is much faster already.
