### ISSUE TITLE
Expand barcode warning/dataspec error

### ISSUE THREAD

**Issue by stoeter** [knime-mpicbg/HCS-Tools#62]
the node gives this error:

ERROR    Expand Barcode                  DataSpec generated by configure does not match spec after execution.

or this warning:

WARN     ExpandPlateBarcode              Could not determine the available barcode attributes because the domain (set of all possible values)
 of the barcode-column is missing.The node will in most cases still work as expected, but Knime will show a warning (red cross) about a the unexpected change of the DatSpec after the execution.
To avoid this problem insert a 'Domain Calculator' before the 'Expand Barcode' and configure it to NOT 'Restrict the number of possible values'.

if there are more than 60 barcodes or the domain is not correct. Does that make sense? I think this behaviour is new with last update!?
Martin

**Comment by niederle** [comment]
Issues should be resolved with the new version of that node.
Otherwise please open a new issue.
