### ISSUE TITLE
plate viewer colormap - problems with setting color for thumb

### ISSUE THREAD

**Issue by niederle** [knime-mpicbg/HCS-Tools#7]
If I use right click on a thumb (created by mean of a control before) the thumb seems to jump a little bit away from it's position (is it still the mean?). sometimes a right click opens the color wheel dialog, sometimes it openes a little dialog (see picture). sometimes nothing happens. the color set with the little dialog is taken, while a color set using the color wheel does nothing to the color scale. further, I'd love to set thumbs by defining the numeric position (say a color for -2, 0 and 2). and it would be nice to see the numeric position of new thumbs. sorry for all these points... we might need to talk about the custom colormap in general?

**Comment by fmeyenhofer** [comment]
I am not sure what you see if you right click on a thumb. What is the color wheel?
To change the color of a thumb you need to open the color dialog by double clicking on it.

Concerning the parameter value that corresponds to a particular thumb: The gradient slider itself does not yet know about that. The position is indicated by a value between 0 and 1. So I need to look into linking the gradient slider and the scale...

**Comment by fmeyenhofer** [comment]
Concerning the color dialogues I was not aware, that there are two options:
1) select the thumb (single click), then a right-click on the same thumb opens a contextual (popup dialog) window for the color selection. And indeed, the thumb jumps a bit if you don't hit the right click in the middle.
2) double click on any thumb opens the color dialog (or color wheel). But if I confirm the dialog by clicking the "OK" button the color applies (in my hands...)
