### ISSUE TITLE
Number Formatter - how to deal with very small numbers

### ISSUE THREAD

**Issue by niederle** [knime-mpicbg/HCS-Tools#99]
There might be values represented as 5.0E-32 (string respresentation)
The node needs to handle them correctly.

**Comment by stoeter** [comment]
How about a choice (pull-down or check box) for "scientific" number formats?
Its complex and the first part (5.0) needs to be handled independently with filling zeros/spaces/underscores where as the last part (-32) could be forces into a two digit number by default (=> 1.0E-123 would be = 0 and 1.0E+123 would be infinity)

**Comment by niederle** [comment]
I could fix the problem but for now the node won't support a scientific format. I will open a new feature issue for this.
